
spring.application.name=shorter
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=${DATABASE_DIALECT}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=1721800000
logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG

frontend.url=${FRONTEND_URL}