spring.application.name=shorter
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=root
spring.datasource.password=sankalp08
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a739a88470a64c952af6326da1e40f4570bf850a1a1907fd48e66c2b923c2ec4
jwt.expiration=1721800000;